package net.vansencool.vanta.symbol.type.ref.var;

import net.vansencool.vanta.symbol.registry.TypeRegistry;
import net.vansencool.vanta.symbol.type.TypeRef;
import net.vansencool.vanta.symbol.type.TypeSymbol;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.List;

/**
 * A reference to a generic type parameter ({@code T}, {@code E}, etc.).
 * Carries the erasure (first bound, defaults to {@code java/lang/Object})
 * so generated bytecode descriptors match javac's erasure rules.
 */
public final class TypeVariableRef implements TypeRef {

    private final @NotNull String name;
    private final @NotNull String erasureInternalName;

    public TypeVariableRef(@NotNull String name) {
        this(name, "java/lang/Object");
    }

    public TypeVariableRef(@NotNull String name, @NotNull String erasureInternalName) {
        this.name = name;
        this.erasureInternalName = erasureInternalName;
    }

    @Override
    public @NotNull String descriptor() {
        return "L" + erasureInternalName + ";";
    }

    @Override
    public @NotNull String internalName() {
        return erasureInternalName;
    }

    @Override
    public int arrayDimensions() {
        return 0;
    }

    @Override
    public @NotNull List<TypeRef> typeArguments() {
        return List.of();
    }

    @Override
    public boolean isPrimitive() {
        return false;
    }

    @Override
    public boolean isTypeVariable() {
        return true;
    }

    @Override
    public @NotNull String typeVariableName() {
        return name;
    }

    @Override
    public @Nullable TypeSymbol resolve(@NotNull TypeRegistry registry) {
        return registry.lookup(erasureInternalName);
    }
}
